apiVersion: v1
kind: Service
metadata:
  name: performance-monitoring
spec:
  selector:
    app: performance-monitoring
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
